[Service]
ExecStart=
ExecStart=/usr/sbin/plymouthd --mode=boot --pid-file=/run/plymouth/pid --attach-to-session --tty=/dev/tty1 --ignore-serial-consoles --graphical-boot --debug-file=/var/log/mi9t-plymouth.log
TimeoutStartSec=10
TimeoutStopSec=5
SendSIGKILL=yes
